# Generated by Django 6.1.1 on 2026-10-07 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('feature_post', 'Can feature a post')]},
        ),
    ]
